"""v3_enhancements

Revision ID: 322013cc0682
Revises: d2f136fb6ef9
Create Date: 2026-05-09 08:31:32.153163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322013cc0682'
down_revision = 'd2f136fb6ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=8), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('protein_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uniprot_id', sa.String(length=32), nullable=True),
    sa.Column('pdb_id', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('sequence_hash', sa.String(length=64), nullable=True),
    sa.Column('pdb_file_path', sa.String(length=512), nullable=True),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('plddt_mean', sa.Float(), nullable=True),
    sa.Column('organism', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protein_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protein_structures_pdb_id'), ['pdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protein_structures_sequence_hash'), ['sequence_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_protein_structures_uniprot_id'), ['uniprot_id'], unique=False)

    op.create_table('mission_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'level')
    )
    with op.batch_alter_table('mission_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_progress_user_id'), ['user_id'], unique=False)

    op.create_table('user_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_slug', sa.String(length=64), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['badge_slug'], ['badges.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    op.create_table('user_xp',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('auto_experiment_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=True),
    sa.Column('rounds_planned', sa.Integer(), nullable=True),
    sa.Column('rounds_completed', sa.Integer(), nullable=True),
    sa.Column('molecules_per_round', sa.Integer(), nullable=True),
    sa.Column('best_candidate_id', sa.UUID(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['best_candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_experiment_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auto_experiment_runs_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('docking_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('docking_score_kcal', sa.Float(), nullable=True),
    sa.Column('docking_score_norm', sa.Float(), nullable=True),
    sa.Column('pose_pdbqt_path', sa.String(length=512), nullable=True),
    sa.Column('exhaustiveness', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['protein_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('docking_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docking_results_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('auto_experiment_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auto_run_id', sa.UUID(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('seed_smiles', sa.Text(), nullable=False),
    sa.Column('candidates_tried', sa.Integer(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('prev_best_score', sa.Float(), nullable=True),
    sa.Column('improved', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['auto_run_id'], ['auto_experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_experiment_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auto_experiment_rounds_auto_run_id'), ['auto_run_id'], unique=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docking_score_kcal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('novelty_status', sa.String(length=16), nullable=True))

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=8), nullable=True, server_default='2d'))
    op.execute("UPDATE experiments SET mode = '2d' WHERE mode IS NULL")
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.alter_column('mode', nullable=False)
        batch_op.add_column(sa.Column('target_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('target_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('uniprot_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('pdb_id', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('protein_structure_id', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_column('protein_structure_id')
        batch_op.drop_column('pdb_id')
        batch_op.drop_column('uniprot_id')
        batch_op.drop_column('target_name')
        batch_op.drop_column('target_id')
        batch_op.drop_column('mode')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('novelty_status')
        batch_op.drop_column('docking_score_kcal')

    with op.batch_alter_table('auto_experiment_rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auto_experiment_rounds_auto_run_id'))

    op.drop_table('auto_experiment_rounds')
    with op.batch_alter_table('docking_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docking_results_candidate_id'))

    op.drop_table('docking_results')
    with op.batch_alter_table('auto_experiment_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auto_experiment_runs_experiment_id'))

    op.drop_table('auto_experiment_runs')
    op.drop_table('user_xp')
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))

    op.drop_table('user_badges')
    with op.batch_alter_table('mission_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_progress_user_id'))

    op.drop_table('mission_progress')
    with op.batch_alter_table('protein_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protein_structures_uniprot_id'))
        batch_op.drop_index(batch_op.f('ix_protein_structures_sequence_hash'))
        batch_op.drop_index(batch_op.f('ix_protein_structures_pdb_id'))

    op.drop_table('protein_structures')
    op.drop_table('badges')
    # ### end Alembic commands ###
