"""game_progression_tables_and_session_fields

Revision ID: 49e701d0451a
Revises: b07a81690921
Create Date: 2026-05-11 16:23:40.149741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e701d0451a'
down_revision = 'b07a81690921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('smiles', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('avg_damage', sa.Float(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boss_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boss_memory_target_id'), ['target_id'], unique=False)

    op.create_table('lab_upgrades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('cost_rp', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.String(length=32), nullable=False),
    sa.Column('effect_value', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('game_leaderboard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mol_name', sa.String(length=64), nullable=False),
    sa.Column('smiles', sa.Text(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('attacks_count', sa.Integer(), nullable=False),
    sa.Column('won_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_leaderboard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_leaderboard_target_id'), ['target_id'], unique=False)

    op.create_table('user_lab_upgrades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('upgrade_slug', sa.String(length=32), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_slug'], ['lab_upgrades.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_research_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('coop_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('analyst_user_id', sa.UUID(), nullable=True),
    sa.Column('analyst_annotations', sa.JSON(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analyst_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('active_mutations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('outbreak_mode', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('outbreak_started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('bad_streak', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('pinned_smiles', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_column('pinned_smiles')
        batch_op.drop_column('bad_streak')
        batch_op.drop_column('outbreak_started_at')
        batch_op.drop_column('outbreak_mode')
        batch_op.drop_column('active_mutations')
        batch_op.drop_column('phase')

    op.drop_table('coop_sessions')
    op.drop_table('user_research_points')
    op.drop_table('user_lab_upgrades')
    with op.batch_alter_table('game_leaderboard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_leaderboard_target_id'))

    op.drop_table('game_leaderboard')
    op.drop_table('lab_upgrades')
    with op.batch_alter_table('boss_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boss_memory_target_id'))

    op.drop_table('boss_memory')
    # ### end Alembic commands ###
