"""Add game_session and game_attack tables

Revision ID: b07a81690921
Revises: 7b4865b47122
Create Date: 2026-05-10 09:02:23.856161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07a81690921'
down_revision = '7b4865b47122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('boss_initial_hp', sa.Float(), nullable=False),
    sa.Column('boss_current_hp', sa.Float(), nullable=False),
    sa.Column('attacks_count', sa.Integer(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('win_threshold', sa.Float(), nullable=False),
    sa.Column('time_started', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_ended', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_session_user_id'), ['user_id'], unique=False)

    op.create_table('game_attack',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('smiles', sa.Text(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('qed', sa.Float(), nullable=True),
    sa.Column('sas', sa.Float(), nullable=True),
    sa.Column('logp', sa.Float(), nullable=True),
    sa.Column('mw', sa.Float(), nullable=True),
    sa.Column('damage_dealt', sa.Float(), nullable=True),
    sa.Column('boss_hp_after', sa.Float(), nullable=False),
    sa.Column('lipinski_pass', sa.Boolean(), nullable=True),
    sa.Column('is_best', sa.Boolean(), nullable=True),
    sa.Column('attack_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_attack', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_attack_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_attack', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_attack_session_id'))

    op.drop_table('game_attack')
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_session_user_id'))

    op.drop_table('game_session')
    # ### end Alembic commands ###
